### ISSUE TITLE
Playground seems not work ...

### ISSUE THREAD

**Issue by nuo-li** [RALF-Life/engine#1]
Dear RALF team, your playground seems not work: https://engine.ralf.life/process

**Comment by darmiel** [comment]
> Dear RALF team, your playground seems not work: https://engine.ralf.life/process 

Hi, you need to POST your contents  with the content type text/yaml- the it should work 😊

**Comment by darmiel** [comment]
> Dear RALF team, your playground seems not work: https://engine.ralf.life/process

cc/ @nuo-li 
This request works for me: https://hopp.sh/r/BY7XZ0nHGHd0

**Comment by nuo-li** [comment]
Yesss! It works!
